---
title: "Nested tables"
output:  
  html_document:  
    toc: true   
    toc_depth: 2  
    toc_float: true
toc-title: "Table of Contents"
---

# Set up

```{r packages, collapse=TRUE}
library(gtsummary)
library(tidyverse)
library(srvyr)
library(flextable)
library(officer)
library(labelled)
library(rlang)
```

<br>

Typical theme for gtsummary()

```{r set theme}

# For all I use the compact theme.
theme_gtsummary_compact()

```

<br>

Load Round 10 UK European Social Survey dataset. 

```{r}

ddir <- paste0(getwd())
load(paste0(ddir,"/ESS_UK_snippet_Round 10.RData"))
glimpse(ess10)
look_for(ess10, details = "none")

ess10 <- ess10 %>% 
  mutate(across(all_of(c("lrscale","atchctr","psppsgva","hincfel")), ~fct_drop(.x))) 

ess10 <- ess10 %>% mutate(age3 = case_when(agea <= 34 ~ 1, agea <= 54 ~ 2, agea > 54 ~ 3)) %>% 
  mutate(age3 = factor(age3, levels = c(1,2,3), labels = c("15-34", "35-54", "54+")))
ess10 %>% count(agea)
ess10 %>% count(age3)
var_label(ess10$age3) <- "Age"

svy_df <- ess10 %>% as_survey_design(weights = anweight)

# List all .R files in ddir 
file_paths <- list.files(path = ddir, pattern = "\\.R$", full.names = TRUE, all.files = T) %>% 
  map_chr(., ~str_remove(.x, ddir)) %>% 
  grep("_interim", ., value =T, invert = T) # Drop interim functions, not used.

# Set of functions to be loaded. 
file_paths
```

<br>

## Load functions
```{r, results='hide'}

# Load all functions (make sure no other .R files in this location)
map(file_paths, ~source(paste0(ddir,.x)))

```

<br>

# Nested crosstabulations

This function takes one nesting variable and one predictor, but allows multiple outcomes. 

```{r}

# why is the code below only returning percentages with decimals within the confidence interval?

nested_tables <- function(
    data, # a dataframe
    variables_int, # a vector of variable names (prefers, perhaps requires, factors)
    crossbreak = NULL, # character vector - length 1
    nest = NULL,
    stats_cat_int = "{p}", # character vector for categorical variables
    stats_num_int = "{mean}", # character vector for numeric variables
    ci_int = NULL, # if TRUE then add confidence intervals
    # number of digits for continuous variables, 
    # must be length 1 or same length as number of numeric variables
    num_digits_int = 2, 
    # Can only set split_num_int to TRUE if ci = NULL
    split_num_int = F, # set to TRUE to split continuous variables stats over multiple lines
    sig_int = NULL, 
    caption = NULL,
    bases = NULL, # The object with base descriptions (from base_information() function)
    source = NULL, # A string describing the data source
    footnotes = NULL # Other character strings as footnotes, each on its own line. 
    ) { 
  
  add_conf <- ifelse(is.null(ci_int), F, T)
  add_p <- ifelse(is.null(sig_int), F, T)
  
  if(add_conf == F & add_p == F){
  
  appendages <- function(x){x %>% add_stat_label(location = "column")}
  
  } else if (add_conf == F & add_p == T){
    
      appendages <- function(x){x %>% add_stat_label(location = "column") %>%
        add_p()}
      
  } else if (add_conf == T & add_p == T){
    
        appendages <- function(x){x %>% add_stat_label(location = "column") %>%
        add_p()  %>% 
          add_ci(statistic = 
             list(
              all_categorical() ~ "{conf.low} - {conf.high}", 
              all_continuous() ~ "{conf.low} - {conf.high}"
             ),
             style_fun = list(
               all_categorical() ~ label_style_percent(digits = 0),
               all_continuous() ~ label_style_sigfig(scale = 1, digits = 2)
               )
           )}
        
        } else if (add_conf == T & add_p == F){
    
        appendages <- function(x){x %>% add_stat_label(location = "column") %>%
          add_ci(statistic = 
             list(
              all_categorical() ~ "{conf.low} - {conf.high}", 
              all_continuous() ~ "{conf.low} - {conf.high}"
             ),
             style_fun = list(
               all_categorical() ~ label_style_percent(digits = 0),
               all_continuous() ~ label_style_sigfig(scale = 1, digits = 2)
               )
            )
          }
  }
  
    whether_survey_data <- if(class(data) %>% grep("survey.design", ., value = T) %>% length() > 0){T} else {F}
  
    if(is.null(ci_int)){
      num_type <- ifelse(split_num_int == T, "continuous2", "continuous")
      stats_num_int2 <- if(split_num_int == T){stats_num_int} else{paste0(stats_num_int, collapse = " ")}
    } else {
      num_type <- "continuous"
      stats_num_int2 <- paste0(stats_num_int, collapse = " ")
    }
    
    if(whether_survey_data == F){

    for(i in 1:length(variables_int)){
      
        base_name <- paste0("base_size",i)
        o_lab <- paste0(var_label(data[variables_int[i]], null_action = "fill"))
        data <- data %>% mutate(!!base_name := case_when(
          is.na(across(all_of(c(crossbreak)))) ~ NA, 
          is.na(across(all_of(c(nest)))) ~ NA, 
          is.na(across(all_of(variables_int[i]))) ~ NA, 
          TRUE ~ o_lab), 
          across(all_of(crossbreak), ~fct_drop(.x))
        )
        
        var_label(data[[base_name]]) <- ""
        
    }
      
    var_label(data[["base_size1"]]) <- "Unweighted sample sizes"

    } else if (whether_survey_data == T){
      
        for(i in 1:length(variables_int)){
      
          base_name <- paste0("base_size",i)
          o_lab <- paste0(var_label(data[["variables"]][variables_int[i]], null_action = "fill"))
          data <- data %>% mutate(!!base_name := case_when(
            is.na(across(all_of(c(crossbreak)))) ~ NA, 
            is.na(across(all_of(c(nest)))) ~ NA, 
            is.na(across(all_of(variables_int[i]))) ~ NA, 
            TRUE ~ o_lab), 
            across(all_of(crossbreak), ~fct_drop(.x))
          )
          
          var_label(data[["variables"]][[base_name]]) <- ""
        
    }
      
    var_label(data[["variables"]][["base_size1"]]) <- "Unweighted sample sizes"

    }
    
    base_names <- paste0("base_size",1:length(variables_int))
    crossbreak_var <- rlang::sym(crossbreak)
    
  final_data <- data %>% filter(!is.na(.data[[crossbreak]]) & !is.na(.data[[nest]]))
  
  if(whether_survey_data == T){temp_data <- data[["variables"]]
      } else {temp_data <- data}

  if(whether_survey_data == T){
      summary_fun <- tbl_svysummary
     } else {summary_fun <- tbl_summary
    }

  table <- 
   final_data %>% 
    tbl_strata(strata = {{nest}}, 
               ~.x %>% 
      summary_fun(
            type = all_continuous() ~ num_type,
            include = all_of(variables_int), 
            by = crossbreak_var,
            missing = "no", 
            statistic = list(
              all_categorical() ~ stats_cat_int, 
              all_continuous() ~ stats_num_int2
              ), 
            digits = list(
              all_categorical() ~ 1, 
              all_continuous() ~ num_digits_int
              )
     ) %>% 
      modify_header(
       all_stat_cols() ~ "**{level}**", 
       label ~ "**Variable**"
       ) %>% 
     bold_labels() %>% 
     # add_stat_label(location = "column") %>%
     add_overall(last=F) %>%
     modify_header(stat_0 ~ "**Total**") %>% 
    appendages(), 
  .header = "**{strata}**"
  )

  if(whether_survey_data == T){n_statistic <- "{n_unweighted}"} else {n_statistic <- "{n}"}
    
  base_of_table <- 
      final_data %>% 
         tbl_strata(strata = {{nest}}, 
                 ~.x %>% 
          summary_fun(
            include = all_of(base_names), 
            by = crossbreak_var,
            missing = "no", 
            statistic = list(all_of(base_names) ~ n_statistic),
            digits = list(all_categorical() ~ 0)
          ) %>%
          add_overall(last=F) %>% # non-missing cases for each variable 
          modify_header(
           all_stat_cols() ~ "**{level}**", 
           label ~ "**Variable**", 
           stat_0 ~ "**Total**"
           ) %>%
          bold_labels(), 
      .header = "**{strata}**"
      )
    
    table <- list(table, base_of_table) %>% tbl_stack() 
    
    stat_label_names <- table[["table_body"]] %>% names %>% grep("stat_label", ., value = T) %>% .[-1]

    table <- table %>%
      modify_table_body(
        ~ .x %>% dplyr::select(!all_of(stat_label_names))
      )
    
    if(whether_survey_data == T){
    for(x in c(variables_int, base_names)) {
      table <- table %>%
        modify_table_body(
        ~ .x %>%
          dplyr::mutate(label = case_when(
            label == x ~ var_label(temp_data[x]) %>% unlist,
            TRUE ~ label)
          ))
    }}
    
    # Identify number of header row starting bases
    base_break_row <- which(table[["table_body"]] %>% pull(label) == "Unweighted sample sizes")
    
    # Remove label rows for bases after base 1.
    table <- table %>% modify_table_body(~.x %>%
        filter(!(grepl("base_size([2-9]|[1-9][0-9]|100)", variable, ignore.case = T) & label == "")) %>%
        add_row(.before = base_break_row) # Add break between bases and main table
    )
  
  # table <- table %>% modify_footnote(all_stat_cols() ~ NA) 
    
  variables <- c(variables_int, crossbreak, nest)
  
  footnotes <- gtsummary_table_notes(
    bases_info = bases, 
    vars = variables_int, 
    source_note = source, 
    other_footnotes = footnotes
  )

  if (footnotes != ""){
    table <- table %>% modify_source_note(
    source_note = footnotes, 
    text_interpret = "html")
  }
  
  if(is.null(caption)){
   caption <- paste0("<div style='text-align: left; font-weight: bold; color: black'>",
                 "Crosstabulation by ", 
                 var_label(temp_data[[crossbreak]]),
                 ", nested by ", 
                 var_label(temp_data[[nest]]),
                 ".",
                 "</div>")
  } else {
    caption <- paste0("<div style='text-align: left; font-weight: bold; color: black'>", caption,"</div>",
                "<div style='text-align: left; font-style: italic; color: black'>","<br>Crosstabulation by ", 
                 var_label(temp_data[[crossbreak]]),
                 ", nested by ", 
                 var_label(temp_data[[nest]]),
                 ".</div>")
  }
  
  table <- table %>% modify_caption(caption)
  
  if(class(data) %>% grep("survey.design", ., value = T) %>% length() > 0){
    stat_types <- "All statistics shown in this table are weighted."
  } else {stat_types <- "All statistics shown in this table are unweighted."
      }

  table <- table %>% modify_footnote_header(stat_types, columns = contains("stat_label"), replace = F)
  
  return(table)
  
}

writeLines(
  c("nested_tables <- ", # Assignment needs to be added manually
  deparse(nested_tables)), # Extract function code
  paste0(ddir,"/nested_tables.R")) # File name is just the function name 


```

<br> 

# Examples

## Example 1

```{r}
vars_to_use <- c("lrscale", "lrscale_num", "atchctr", "atchctr_num", "psppsgva", "psppsgva_num", "hincfel")

nested_tables(data = ess10, 
       variables_int = vars_to_use,
       crossbreak = "gndr",
       nest = "age3",
       ci_int = T, 
       sig_int = T
       ) 

```

<br>

## Example 1

```{r}

nested_tables(data = svy_df, 
       variables_int = vars_to_use,
       crossbreak = "gndr",
       nest = "age3",
       ci_int = T, 
       sig_int = T
       ) 
```

<br>

## Example 2

```{r}

nested_tables(data = ess10, 
       variables_int = vars_to_use, 
       stats_cat_int = "{p}",
       stats_num_int = c("{mean}", "{median}", "({sd})", "{min}-{max}"),
       num_digits_int = c(2, 0, 1, 0 ,0),
       split_num_int = F, 
       crossbreak = "gndr",
       nest = "age3", 
       caption  = "how do strings work \n around here <br>?"
       # ci_int = T
       ) 
```

<br>

## Example 3

```{r}

nested_tables(data = svy_df, 
       variables_int = vars_to_use, 
       stats_cat_int = "{p}",
       stats_num_int = c("{mean}", "{median}", "({sd})", "{min}-{max}"),
       num_digits_int = c(2, 0, 1, 0 ,0),
       split_num_int = T, 
       crossbreak = "gndr",
       nest = "age3", 
       caption  = "how do strings work \n around here <br>?"
       # ci_int = T
       ) 

```

<br>

## Example 4

```{r}

paste0(c("{mean}", "{median}", "({sd})", "{min}-{max}"), collapse = " ")

nested_tables(data = ess10, 
       variables_int = vars_to_use, 
       crossbreak = c("gndr"),
       nest = "age3",
       stats_cat_int = "{p}",
       stats_num_int = c("{mean}", "({sd})"),
       num_digits_int = c(2, 1),
       split_num_int = T, 
       ci_int = T
       ) 

```

