---
title: "Numerics"
output:  
  html_document:  
    toc: true   
    toc_depth: 2  
    toc_float: true
toc-title: "Table of Contents"
---

# Set up

```{r packages, collapse=TRUE}
library(gtsummary)
library(tidyverse)
library(srvyr)
library(flextable)
library(officer)
library(labelled)
library(rlang)
```

<br>

Typical theme for gtsummary()

```{r set theme}

# For all I use the compact theme.
theme_gtsummary_compact()

```

<br>

Load Round 10 UK European Social Survey dataset. 

```{r}

ddir <- "/Users/joecrowley/R/Tables/gtsummary"
load(paste0(ddir,"/ESS_UK_snippet_Round 10.RData"))
glimpse(ess10)

svy_df <- ess10 %>% as_survey_design(weights = anweight)
vars <- c("atchctr_num", "stflife_num", "stfgov_num")

```

<br>

## Identify variables to use 

<br>

```{r}

ess10 %>% glimpse

ess10 %>% select(atchctr_num, stflife_num, stfgov_num) %>% var_label()

```

# Single line summary function

```{r}

nums <- function(
    outcomes,  # character vector with outcomes
    data, 
    stats = "{mean} ({sd})", # Define statistics with a string
    stats_title = "**Mean (SD)**", # this is the default statistic column heading, can be anything
    ci = NULL # if TRUE then add confidence intervals, use when only one stat defined. 
    ) {
  
  table <- data %>%
    tbl_summary(
        include = all_of(outcomes), 
        missing = "no",
        statistic = list(all_continuous() ~ stats), 
        digits = list(all_continuous() ~ 1)
    ) %>% 
    modify_header(all_stat_cols() ~ "**{level}**", label ~ "**Variable**", stat_0 ~ stats_title) %>% 
    modify_footnote(everything() ~ NA) %>%
    add_n(last=TRUE) # non-missing cases for each variable %>% 

if (!is.null(ci)){
 table <- table %>%
  add_ci(statistic = list(all_continuous() ~ "{conf.low} - {conf.high}"),
         style_fun = all_continuous() ~ label_style_sigfig(scale = 1, digits = 2))
}
  
  return(table)
  
}

```

<br> 

## Examples

### Example 1 

```{r}
# Defaults are mean + SD
ess10 %>% nums(outcomes = vars)

```

<br>

### Example 2

```{r}
# Can use other statistics standard for tbl_summary with numerics. 
ess10 %>% nums(outcomes = vars, 
                stats = "{mean} ({sd}) [{min} - {max}]", 
                stats_title = "**Mean (SD) [Range]**", 
                ci = T)

```

<br>

### Example 3

```{r}

# When adding confidence intervals it's not clear what the CI belong to - mean or median? Display only one. 
ess10 %>% nums(outcomes = vars, 
                stats = "{mean}", 
                stats_title = "**Mean**", 
                ci = T)

```

<br>

```{r}

writeLines(
  c("nums <- ", # Assignment needs to be added manually
  deparse(nums)), # Extract function code
  paste0(ddir,"/nums.R")) # File name is just the function name 

```

<br>

# Single line summary function - weights

```{r}

svy_nums <- function(
    outcomes, # character vector with outcomes
    data,  # a srvyr() object
    stats = "{mean} ({sd})", # define statistics with a string
    stats_title = "**Mean (SD)**",  # this is the default statistic column heading, can be anything
    caption = NULL, 
    ci = NULL # if TRUE then add confidence intervals, use when only one stat defined. 
    ) {
  
  table <- data %>%
    tbl_svysummary(
        include = all_of(outcomes), 
        missing = "no",
        statistic = list(all_continuous() ~ stats), 
        digits = list(all_continuous() ~ 1)
    ) %>% 
    modify_header(all_stat_cols() ~ "**{level}**", label ~ "**Variable**", stat_0 ~ stats_title) %>% 
    modify_footnote(everything() ~ NA) %>%
  add_n(statistic = "{N_nonmiss_unweighted}", last=TRUE, col_label = "**N (unw)**") # non-missing cases for each variable 
  
  if (is.null(caption)) {caption <- "Weighted summary statistics"}
  table <- table %>% modify_caption(paste0("<div style='text-align: left; font-weight: bold; color: black'> ", caption, "</div>")) 
  
if (!is.null(ci)){
 table <- table %>%
  add_ci(statistic = list(all_continuous() ~ "{conf.low} - {conf.high}"),
         style_fun = all_continuous() ~ label_style_sigfig(scale = 1, digits = 2))
}
  
  return(table)
  
}

```

<br> 

## Examples

### Example 1 

```{r}

svy_df %>% svy_nums(outcomes = vars, caption = "Insert caption")

```

<br>

### Example 2

```{r}

# Can use other statistics standard for tbl_summary with numerics. 
# Again, use CI when only one of median / mean specified
svy_df %>% svy_nums(outcomes = vars, 
                     stats = "{mean} ({sd}) [{min} - {max}]", 
                     stats_title = "**Mean (SD) [Range]**", 
                     ci = T)

```

<br>

```{r}

writeLines(
  c("svy_nums <- ", # Assignment needs to be added manually
  deparse(svy_nums)), # Extract function code
  paste0(ddir,"/svy_nums.R")) # File name is just the function name 

```

<br>

# Multi line summary - function

```{r}
nums2 <- function(
    outcomes, 
    data, 
    stats = c("{mean}","{median}", "{sd}", "{min} - {max}", "{N_nonmiss}"),
    digits = c(1,1,1,1,1,0)
    ) {
  
data %>%
  tbl_summary(
      type = all_continuous() ~ "continuous2",
      include = all_of(outcomes), 
      missing = "no",
      statistic = list(all_continuous() ~ stats), 
      digits = list(all_continuous() ~ digits)
  ) %>% 
  modify_header(all_stat_cols() ~ "**{level}**", label ~ "**Variable**", stat_0 ~ "**Statistics**") %>%
    bold_labels()

}

```

<br> 

## Examples

### Example 1 

```{r}

ess10 %>% nums2(outcomes = vars)

```

<br>   

### Example 2. 

```{r}

ess10 %>% nums2(outcomes = vars, 
                 stats = c("{mean}", "{median}", "{N_nonmiss}"), 
                 digits = c(2,2,0))

```

<br>

```{r}

writeLines(
  c("nums2 <- ", # Assignment needs to be added manually
  deparse(nums2)), # Extract function code
  paste0(ddir,"/nums2.R")) # File name is just the function name 

```

<br>

# Multi line summary - function + weights

```{r}

svy_nums2 <- function(
    outcomes, 
    data, 
    stats = "default",
    digits = c(1,2,1,1,1,1,0)
    ) {
  
  if ("default" %in% stats){
  stats_to_use <- c("{mean}","{mean.std.error}", "{sd}", "{median}", "{min} - {max}", "{N_nonmiss_unweighted}")
  } else {
    stats_to_use <- stats
  }
  
table <- data %>%
  tbl_svysummary(
      type = all_continuous() ~ "continuous2",
      include = all_of(outcomes), 
      missing = "no",
      statistic = list(all_continuous() ~ stats_to_use), 
      digits = list(all_continuous() ~ digits)
  ) %>% 
  modify_header(all_stat_cols() ~ "**{level}**", label ~ "**Variable**", stat_0 ~ "**Statistics (weighted)**") %>%
    bold_labels() %>% 
    modify_table_body(
    ~ .x %>% dplyr::mutate(label = case_when(label == "N not Missing (unweighted)" ~ "N (unweighted)", TRUE ~ label)))
  
  if ("default" %in% stats){
    table <- table %>% add_stat_label(label = list(all_continuous2() ~ c("Mean", "Mean SE", "Mean SD", "Median", "Range", "N (unw.)")))
  }

return(table)

}

```

<br> 

## Examples

### Example 1 

```{r}
svy_df %>% svy_nums2(outcomes = vars)

```

<br>   

### Example 2. 

```{r}

svy_df %>% svy_nums2(outcomes = vars, 
                 stats = c("{mean}", "{median}", "{N_nonmiss_unweighted}"), 
                 digits = c(2,2,0))

```

<br>

```{r}

writeLines(
  c("svy_nums2 <- ", # Assignment needs to be added manually
  deparse(svy_nums2)), # Extract function code
  paste0(ddir,"/svy_nums2.R")) # File name is just the function name 

```

<br>
