---
title: "Frequencies"
output:  
  html_document:  
    toc: true   
    toc_depth: 2  
    toc_float: true
toc-title: "Table of Contents"
---

# Set up

```{r packages, collapse=TRUE}
library(gtsummary)
library(tidyverse)
library(srvyr)
library(flextable)
library(officer)
library(labelled)
library(rlang)
```

<br>

Typical theme for gtsummary()

```{r set theme}

# For all I use the compact theme.
theme_gtsummary_compact()

```

<br>

Load Round 10 UK European Social Survey dataset. 

```{r}

ddir <- "/Users/joecrowley/R/Tables/gtsummary"
load(paste0(ddir,"/ESS_UK_snippet_Round 10.RData"))
glimpse(ess10)
look_for(ess10, details = "none")

ess10 <- ess10 %>% 
  mutate(across(all_of(c("lrscale","atchctr","psppsgva","hincfel")), ~fct_drop(.x))) 

svy_df <- ess10 %>% as_survey_design(weights = anweight)


```

<br>

# Can nested tables be stacked? 

Yes. 

```{r}

age_tbl <- trial |>
  select(age, grade, trt) |>
  mutate(grade = paste("Grade", grade)) |>
  tbl_strata(
    strata = grade,
    .tbl_fun =
      ~ .x |>
        tbl_summary(by = trt, missing = "no") |>
        add_n(),
    .header = "**{strata}**, N = {n}"
  )

stage_tbl <- trial |>
  select(grade, stage, trt) |>
  mutate(grade = paste("Grade", grade)) |>
  tbl_strata(
    strata = grade,
    .tbl_fun =
      ~ .x |>
        tbl_summary(by = trt, missing = "no") |>
        add_n(),
    .header = "**{strata}**, N = {n}"
  )

tbl_stack(list(age_tbl, stage_tbl))

```

# Can if statements be used within the nested table formula?

No. 

```{r, error=T}

add_conf = T

trial |>
  select(grade, stage, trt) |>
  mutate(grade = paste("Grade", grade)) |>
  tbl_strata(
    strata = grade,
    .tbl_fun =
      result <- ~.x |>
        tbl_summary(by = trt, missing = "no") |>
        add_n()
    
      if(add_conf == T){result <- result %>% add_ci()}
    ,
    .header = "**{strata}**, N = {n}"
  )

```

# Can user-defined combinations of functions be applied? 

Probably. 

```{r}

add_conf = T
add_p = T

if(add_conf == F & add_p == F){
  
  appendages <- function(x){x %>% add_stat_label(location = "column")}
  
} else if (add_conf == F & add_p == T){
  
    appendages <- function(x){x %>% add_stat_label(location = "column") %>%
      add_p()}
    
} else if (add_conf == T & add_p == T){
  
      appendages <- function(x){x %>% add_stat_label(location = "column") %>%
      add_p()  %>% 
        add_ci(statistic = 
           list(
            all_categorical() ~ "{conf.low} - {conf.high}", 
            all_continuous() ~ "{conf.low} - {conf.high}"
           ),
           style_fun = list(
             all_categorical() ~ label_style_percent(digits = 0),
             all_continuous() ~ label_style_sigfig(scale = 1, digits = 2)
             )
         )}
      
      } else if (add_conf == T & add_p == F){
  
      appendages <- function(x){x %>% add_stat_label(location = "column") %>%
        add_ci(statistic = 
           list(
            all_categorical() ~ "{conf.low} - {conf.high}", 
            all_continuous() ~ "{conf.low} - {conf.high}"
           ),
           style_fun = list(
             all_categorical() ~ label_style_percent(digits = 0),
             all_continuous() ~ label_style_sigfig(scale = 1, digits = 2)
             )
          )
        }
}

triale_table <- trial |>
  select(grade, stage, trt) |>
  mutate(grade = paste("Grade", grade)) |>
  tbl_strata(
    strata = grade,
    .tbl_fun =
      ~ .x |>
        tbl_summary(by = trt, missing = "no") |>
        add_n() |> 
      appendages(),
    .header = "**{strata}**, N = {n}"
  )  

triale_table

```

# How do I remove those extra stata labels? 

```{r}
triale_table[["table_body"]]

stat_label_names <- triale_table[["table_body"]] %>% names %>% grep("stat_label", ., value = T) %>% .[-1]

triale_table %>%
  modify_table_body(
    ~ .x %>% dplyr::select(!all_of(stat_label_names))
  )


```

# Can nested tables be merged to un-nested ones? 

Yes.

```{r}

tbl <- trial |>
  select(stage, trt) |>
        tbl_summary(by = trt, missing = "no") |>
        add_n()
  
tbl_merge(list(tbl, stage_tbl), tab_spanner = F)

```




