---
title: "Frequencies"
output:  
  html_document:  
    toc: true   
    toc_depth: 2  
    toc_float: true
toc-title: "Table of Contents"
---

# Set up

```{r packages, collapse=TRUE}
library(gtsummary)
library(tidyverse)
library(srvyr)
library(flextable)
library(officer)
library(labelled)
library(rlang)
```

<br>

Typical theme for gtsummary()

```{r set theme}

# For all I use the compact theme.
theme_gtsummary_compact()

```

<br>

Load Round 10 UK European Social Survey dataset. 

```{r}

ddir <- "/Users/joecrowley/R/Tables/gtsummary"
load(paste0(ddir,"/ESS_UK_snippet_Round 10.RData"))
glimpse(ess10)
look_for(ess10, details = "none")

ess10 <- ess10 %>% 
  mutate(across(all_of(c("lrscale","atchctr","psppsgva","hincfel")), ~fct_drop(.x))) 

svy_df <- ess10 %>% as_survey_design(weights = anweight)


```

<br>

```{r}

# why is the code below only returning percentages with decimals within the confidence interval?

totals <- function(data, # a dataframe
                  variables, # a vector of variable names (prefers, perhaps requires, factors)
                  stats_cat = "{p}", # character vector for categorical variables
                  stats_num = "{mean}", # character vector for numeric variables
                  caption = NULL, # character vector, used if not NULL
                  ci = NULL, # if TRUE then add confidence intervals
                  num_digits = 2, # number of digits for continuous variables, must be length 1 or same length as number of numeric variables
                  
                  # Can only set split_num to TRUE if ci = NULL
                  split_num = F # set to TRUE to split continuous variables stats over multiple lines
                  ) { 

  if(is.null(ci)){
  num_type <- ifelse(split_num == T, "continuous2", "continuous")
  } else {num_type <- "continuous"}

 table <- 
  data %>% 
  tbl_summary(
          type = all_continuous() ~ num_type,
          include = all_of(variables), 
          missing = "no", 
          statistic = list(
            all_categorical() ~ stats_cat, 
            all_continuous() ~ stats_num
            ), 
          digits = list(
            all_categorical() ~ 1, 
            all_continuous() ~ num_digits
            )
  ) %>% 
  modify_header(
    all_stat_cols() ~ "**{level}**", 
    label ~ "**Variable**"
    ) %>% 
  bold_labels() %>% 
  add_n(last=TRUE)  %>% 
   add_stat_label(location = "column")
 
 if (!is.null(ci)){
   
   table <- table %>% add_ci(statistic = 
     list(
      all_categorical() ~ "{conf.low} - {conf.high}", 
      all_continuous() ~ "{conf.low} - {conf.high}"
     ),
     style_fun = list(
       all_categorical() ~ label_style_percent(digits = 0),
       all_continuous() ~ label_style_sigfig(scale = 1, digits = 2)
       )
   )   
 }
  
  return(table)
  
}

vars_to_use <- c("lrscale", "lrscale_num", "atchctr", "atchctr_num", "psppsgva", "psppsgva_num", "hincfel")
totals(data = ess10, 
       variables = vars_to_use,
       ci = T
       ) 

totals(data = ess10, 
       variables = vars_to_use, 
       stats_cat = "{p} [{n}]",
       ci = T
       ) 

totals(data = ess10, 
       variables = vars_to_use, 
       stats_num = "{mean} ({sd})",
       num_digits = c(2, 1),
       ci = T
       ) 

totals(data = ess10, 
       variables = vars_to_use, 
       stats_num = c("{mean}", "({sd})"),
       num_digits = c(2, 1),
       split_num = T
       # ci = T
       ) 

totals(data = ess10, 
       variables = vars_to_use, 
       stats_cat = "{p}",
       stats_num = c("{mean}", "{median}", "({sd})", "{min}-{max}"),
       num_digits = c(2, 0, 1, 0 ,0),
       split_num = T
       # ci = T
       ) 



```
























