---
title: "Trialing changing functions within a function"
output: html_document
date: "2025-12-14"
---

```{r setup}
library(gtsummary)
```

# Set up some data

```{r}
data(api, package = "survey")

apiclus1 %>% 
  tbl_summary(by = "both", include = c(api00, stype)) |>
  modify_spanning_header(all_stat_cols() ~ "**Survived**")

svy_data <- survey::svydesign(id = ~dnum, weights = ~pw, data = apiclus1, fpc = ~fpc) 

svy_data |>
  tbl_svysummary(by = "both", include = c(api00, stype)) |>
  modify_spanning_header(all_stat_cols() ~ "**Survived**")

```

<br> 

# Test function

```{r}

my_summary <- function(data, by = NULL, survey_design = FALSE) {
  
  summary_fun <- if (survey_design) {
    tbl_svysummary
  } else {
    tbl_summary
  }
  
  result <- summary_fun(
    data = data,
    include = c(api00, stype),
    by = by,
  )
  
  return(result)
}

my_summary(
  data = apiclus1,
  by = "both",
  survey_design = FALSE
)

my_summary(
  data = svy_data,
  by = "both",
  survey_design = T
)

```

<br>

# What about simply code snippets? 

```{r}

# Check whether survey data or not (T = survey; F = data frame)
# If survey referece appropriate part of survey object
# Otherwise, reference the data frame normally
dataset_reference <- function(df){
  
  whether_survey_data <- if(
     class(df) %>% 
      grep("survey.design", ., value = T) %>% 
      length() > 0
    ){T} else {F}

  if(whether_survey_data == F){df} else {df[["variables"]]}
  }

dataset_reference(svy_data)
dataset_reference(apiclus1)

# The above erturns the data frame, that's not quite what I want
# What I want is the unevaluated expression
# hmmm, dunno

```







