---
title: "7 Sort bases"
output: html_document
date: "2025-12-06"
---

# Re-ordering bases

This file takes the unweighted bases from each variable and groups them at the bottom of the table under the relevant variable label. 

```{r setup, include=FALSE}

# Easiest to copy all these packages into a script using these functions
library(tidyverse)
library(labelled)
library(gtsummary)
library(huxtable)
library(openxlsx)
library(haven)

# For all I use the compact theme.
theme_gtsummary_compact()

# Load BSA teaching data
df <- read_sav('/Users/joecrowley/R/Data/BSA Teaching Data/spss/spss25/bsa2019_poverty_open.sav', user_na = T)
df <- df %>% mutate(across(c(skipmeal, RSex, HEdQual3, Dole), ~fct_drop(to_factor(.x, user_na_to_na = T))))

# Available files
# List all .R files in ddir 
ddir <- "/Users/joecrowley/R/Tables/gtsummary"

file_paths <- list.files(path = ddir, pattern = "\\.R$", full.names = TRUE, all.files = T) %>% 
  map_chr(., ~str_remove(.x, ddir))

# Load all functions (make sure no other .R files in this location)
map(file_paths, ~source(paste0(ddir,.x)))

# Show function code... 
cbreaks

tbl <- df %>% cbreaks(outcome = c("skipmeal", "Dole"), crossbreak = "RSex")

tbl

```


```{r}

data <- df
outcome <- "Dole"
crossbreak <- "RSex"
ci <- F


cbreak_interim2 <- 
  function(data, # dataframe
         outcome,  # character vector
         crossbreak, # character vector - length 1
         ci = FALSE # set to TRUE for CI
  ){

cross_break <- list()
bases <- list()

for (i in 1:length(outcome)) {
  
o_var <- outcome[i]
by_var <- crossbreak
base_name <- paste0("base_size",i)
o_lab <- paste0(var_label(df[o_var], null_action = "fill"))

df_tmp <- data %>% 
  select(all_of(c(outcome, by_var))) %>%
  mutate(!!base_name := case_when(is.na(.data[[by_var]]) ~ NA, is.na(.data[[o_var]]) ~ NA, TRUE ~ o_lab)) 

var_label(df_tmp[[base_name]]) <- ""

if(base_name == "base_size1"){var_label(df_tmp[[base_name]]) <- "Unweighted sample sizes"}

perc <- 
  df_tmp %>%
  tbl_summary(
  include = all_of(c(o_var)), 
  by = .data[[by_var]],
  missing = "no", 
  statistic = list(all_categorical() ~ "{p}"),
  digits = list(all_categorical() ~ 0)
  ) %>%
  add_stat_label(location = "column") %>% 
  add_overall(last=F) %>% # non-missing cases for each variable 
  modify_header(all_stat_cols() ~ "**{level}**", 
                label ~ "**Variable**",
                stat_0 ~ "**Total**",
                stat_label ~ "")  %>%
  bold_labels() %>% 
  add_p()

base_of_table <- 
    df_tmp %>%
      tbl_summary(
      include = all_of(base_name), 
      by = .data[[by_var]],
      missing = "no", 
      statistic = list({{base_name}} ~ "{n}"),
      digits = list(all_categorical() ~ 0)
      ) %>%
      add_stat_label(label = {{base_name}} ~ "", location = "column") %>% 
      add_overall(last=F) %>% # non-missing cases for each variable 
      modify_header(all_stat_cols() ~ "**{level}**", 
                    label ~ "**Variable**",
                    stat_0 ~ "**Total**",
                    stat_label ~ "")  %>%
      bold_labels() 

if (ci == TRUE) {
perc <- perc %>% 
   add_ci(
     statistic = list(all_categorical() ~ "[{conf.low} - {conf.high}]"),
     style_fun = all_categorical() ~ label_style_sigfig(scale = 100, digits = 1))
}

cross_break[[i]] <- perc
bases[[i]] <- base_of_table

}

table <- 
  append(cross_break, bases) %>% tbl_stack() %>% 
  modify_caption("<div style='text-align: left; font-weight: bold; color: black'> Unweighted percentages</div>") %>%
  modify_footnote(all_stat_cols() ~ NA) %>%
  modify_spanning_header(
    all_stat_cols() ~ paste0("**",var_label(data[[by_var]]),"**"),
    starts_with("ci_stat") ~ paste0("**",var_label(data[[by_var]]),"**"), # Added to ensure CI included in spanning headers
    ends_with("_0") ~ NA) # suppress spanning header on total column

base_break_row <- which(table[["table_body"]] %>% pull(label) == "Unweighted sample sizes")

table <- table %>% modify_table_body(
   ~ .x %>%
     filter(!(grepl("base_size([2-9]|[1-9][0-9]|100)", variable, ignore.case = T) & label == "")) %>%
     # filter(!(grepl("^base_size([2-9]|10)$", variable, ignore.case = T) & label == "")) %>%
     add_row(.before = base_break_row)
 )

return(table)

  }

test_table <- 
  cbreak_interim2(data =df, 
                outcome = c("HEdQual3", "skipmeal"), 
                crossbreak = "RSex"
                )

test_table

base_break_row <- which(test_table[["table_body"]] %>% pull(label) == "Unweighted sample sizes")

test_table %>% modify_table_body(
   ~ .x %>%
     filter(!(grepl("^base_size([2-9]|10)$", variable, ignore.case = T) & label == "")) %>%
     add_row(.before = base_break_row)
 )

test_table[["table_body"]]

```

