---
title: "freq_spss data dictionary example"
output: 
  html_document:  
    toc: true   
    toc_depth: 2  
    toc_float: true
toc-title: "Table of Contents"
---

```{r packages, collapse = T}

library(haven)
library(tidyverse)
library(labelled)
library(flextable)

```

```{r load data}

# Load BSA teaching data
df <- read_sav('/Users/joecrowley/R/Data/BSA Teaching Data/spss/spss25/bsa2019_poverty_open.sav', user_na = T)
source("/Users/joecrowley/R/The-quackery/freq_spss.R")
variables <- names(df)

```

# Contents

```{r, results = 'asis'}

for(xxx in variables){
  
  label <- var_label(df[xxx], unlist = T) 
  levels <- df %>% pull(xxx) %>% to_factor(levels = "prefixed", nolabel_to_na = T) %>% levels()
  
  cat("\n")
  
  cat(" * ", paste0("[",xxx,"]"), ": - ", label, "  \n")
  
  cat("\n")
  
}

```

<br> 

# Variables

```{r, results = 'asis', eval=TRUE}

for(xxx in variables){
  
  cat("\n")
  cat("##", xxx, " \n")
  
  cat("[Contents]")
  cat("\n")
  
  freq_spss(data = df, var = !!sym(xxx), format = TRUE) %>% flextable_to_rmd()

  cat("\n<br>\n")
  

}

```

